spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: user-service
      profile: dev
      uri: http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_user
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8081

app:
  jwt:
    secret: mySecretKey12345678901234567890123456789012345678901234567890
    expiration: 86400000 # 24 hours

logging:
  level:
    com.ecommerce.user: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
