spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: inventory-service
      profile: dev
      uri: http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 2
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8085

# Redisson configuration
redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      database: 2
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500

logging:
  level:
    com.ecommerce.inventory: DEBUG
    org.springframework.transaction: DEBUG
