groups:
  - name: ecommerce-platform-alerts
    rules:
      # 系統健康檢查告警
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.job }} service on {{ $labels.instance }} has been down for more than 1 minute."

      # JVM 內存使用率告警
      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "JVM heap memory usage is above 80% on {{ $labels.instance }}"

      # CPU 使用率告警
      - alert: HighCpuUsage
        expr: system_cpu_usage > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% on {{ $labels.instance }} for more than 5 minutes"

      # HTTP 錯誤率告警
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) / rate(http_server_requests_seconds_count[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for {{ $labels.instance }}"

      # 響應時間告警
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second for {{ $labels.instance }}"

      # 數據庫連接池告警
      - alert: DatabaseConnectionPoolLow
        expr: hikaricp_connections_active / hikaricp_connections_max > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Database connection pool usage high"
          description: "Database connection pool usage is above 80% on {{ $labels.instance }}"

      # 業務指標告警
      - alert: HighOrderFailureRate
        expr: rate(order_created_count{status="failed"}[5m]) / rate(order_created_count[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High order failure rate"
          description: "Order failure rate is above 5% for {{ $labels.instance }}"

      - alert: LowInventoryAlert
        expr: inventory_products_low_stock > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Multiple products with low inventory"
          description: "{{ $value }} products have low inventory levels"

      - alert: OutOfStockAlert
        expr: inventory_products_out_of_stock > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Multiple products out of stock"
          description: "{{ $value }} products are out of stock"

      # 用戶服務告警
      - alert: HighLoginFailureRate
        expr: rate(user_login_count{status="failed"}[5m]) / rate(user_login_count[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High login failure rate"
          description: "Login failure rate is above 10% - possible security issue"

      # Redis 連接告警
      - alert: RedisConnectionDown
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection lost"
          description: "No clients connected to Redis on {{ $labels.instance }}"

      # Kafka 消費延遲告警
      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag_sum > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Kafka consumer lag"
          description: "Kafka consumer lag is above 1000 messages on {{ $labels.instance }}"

      # 磁盤空間告警
      - alert: DiskSpaceLow
        expr: (disk_free_bytes / disk_total_bytes) * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 10% on {{ $labels.instance }}"

      # 網絡連接告警
      - alert: TooManyOpenConnections
        expr: netstat_tcp_socket{state="established"} > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many open TCP connections"
          description: "Number of established TCP connections is above 1000 on {{ $labels.instance }}"
