global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 告警規則文件
rule_files:
  - "alert-rules.yml"

# 告警管理配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Eureka Server 監控
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Config Server 監控
  - job_name: 'config-server'
    static_configs:
      - targets: ['config-server:8888']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # API Gateway 監控
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # User Service 監控
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Product Service 監控
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Cart Service 監控
  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Order Service 監控
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Inventory Service 監控
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # Notification Service 監控
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8086']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
