server:
  port: 8086

spring:
  # Mail configuration for notifications
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: true
  
  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Logging configuration  
logging:
  level:
    com.ecommerce.notification: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Application specific configuration
notification:
  email:
    from: noreply@ecommerce.com
    templates:
      order-created: order-created
      order-confirmed: order-confirmed
      order-shipped: order-shipped
      order-delivered: order-delivered
      order-cancelled: order-cancelled
      inventory-low: inventory-low
      welcome: welcome
